Algoritmo "Estrutura de repetição"

Var
   contador, valor, salto : inteiro


Inicio
      contador <- 0
      escreva ("Quer contar ate quanto? ")
      leia (valor)
      escreva ("Qual o valor do salto? ")
      leia (salto)
      enquanto (contador <= valor) faca
               escreval (contador)
               contador <- contador + salto
      fimenquanto
      escreva ("Fim da contagem")


Fimalgoritmo