Algoritmo "multiplicacao e potenciacao"

Var
   N1, N2: inteiro
   M: real
   EX: inteiro
   EL: real
   
   


Inicio
     escreva ("Informe um numero:")
     leia (N1)
     escreva ("Informe outro numero:")
     leia (N2)
     M <- N1*N2
     escreval ("A multiplicação entre", N1, " e", N2, " é igual a:", M)
     escreval ("Informe um numero para ser o expoente de", M )
     leia (EX)
     El <- M^EX
     escreva (M, " elevado a", EX, " é igual a", EL)


Fimalgoritmo