Algoritmo "Senha"

Var
   senha,tentativa: inteiro



Inicio
      senha <- 1234

      escreva ("Digite a senha: ")
      leia (tentativa)
      
      enquanto tentativa <> senha faca
               escreval ("Senha incorreta, tente novamente.")
               escreva ("Digite a senha: ")
               leia (tentativa)
               
      fimenquanto

      escreva ("Acesso permitido!")




Fimalgoritmo