Algoritmo "loopsomatoria"

Var
   numero, soma: inteiro
procedimento Soma()
 =
inicio
      soma <- soma + numero
        escreva ("Digite um número (0 para parar):")
        leia (numero)

fimprocedimento

Inicio

      escreva ("Digite um número (0 para parar):")
      leia (numero)
      
      enquanto numero <> 0 faca
        oma()
      fimenquanto
      
      escreva ("A soma total é", soma)
        
               

      
      


Fimalgoritmo